# Generated by Django 4.2 on 2024-08-13 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('note', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.colors'),
        ),
        migrations.AddField(
            model_name='note',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.ManyToManyField(to='note.tags'),
        ),
        migrations.AddField(
            model_name='colors',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tags',
            unique_together={('profile', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='colors',
            unique_together={('profile', 'color')},
        ),
    ]
